# Generated by Django 5.2.8 on 2025-11-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area_m2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cosecha', models.DateField()),
                ('rendimiento_kg', models.FloatField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cultivos.cultivo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='cosechas.lote')),
            ],
        ),
    ]
