# Generated by Django 5.2.8 on 2025-11-22 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaPerdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('causa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perdidas.causaperdida')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidas', to='cultivos.cultivo')),
            ],
        ),
    ]
